Función para generar una matriz aleatoria

In [4]:
import numpy as np

def generar_matriz_simetrica_con_ceros_enteros(tamaño, rango_inicio=10, rango_fin=100):
    # Generar una matriz aleatoria cuadrada de enteros
    matriz = np.random.randint(rango_inicio, rango_fin, size=(tamaño, tamaño), dtype=int)

    # Hacer la matriz simétrica
    matriz_simetrica = (matriz + matriz.T)

    # Establecer ceros en la diagonal
    np.fill_diagonal(matriz_simetrica, 0)

    return matriz_simetrica

# Ejemplo de uso:
tamaño = 5
matriz_simetrica_ceros_enteros = generar_matriz_simetrica_con_ceros_enteros(tamaño)

print("Matriz Simétrica con Ceros en la Diagonal (enteros):")
print(matriz_simetrica_ceros_enteros)


Matriz Simétrica con Ceros en la Diagonal (enteros):
[[  0 104 121  81 146]
 [104   0 189  90  31]
 [121 189   0  83 106]
 [ 81  90  83   0 102]
 [146  31 106 102   0]]


In [2]:
import numpy as np

def generar_matriz_simetrica_con_ceros_enteros(tamaño, rango_inicio=10, rango_fin=100):
    # Generar una matriz aleatoria cuadrada de enteros
    matriz = np.random.randint(rango_inicio, rango_fin, size=(tamaño, tamaño), dtype=int)

    # Hacer la matriz simétrica
    matriz_simetrica = (matriz + matriz.T) // 2  # Corregir la simetría

    # Establecer ceros en la diagonal
    np.fill_diagonal(matriz_simetrica, 0)

    return matriz_simetrica

# Ejemplo de uso:
tamaño = 5
matriz_simetrica_ceros_enteros = generar_matriz_simetrica_con_ceros_enteros(tamaño)

print("Matriz Simétrica con Ceros en la Diagonal (enteros):")
# Imprimir la matriz con comas

for fila in matriz_simetrica_ceros_enteros:
    # Itera sobre cada fila en la matriz

    # Utiliza map(str, fila) para convertir cada elemento de la fila en cadena
    # Luego, utiliza ", ".join(...) para unir esos elementos con comas
    fila_coma_separada = ", ".join(map(str, fila))

    # Imprime la fila con comas entre cada elemento
    print(fila_coma_separada)


Matriz Simétrica con Ceros en la Diagonal (enteros):
0, 79, 47, 45, 42
79, 0, 73, 51, 30
47, 73, 0, 40, 30
45, 51, 40, 0, 49
42, 30, 30, 49, 0
