In [1]:
! pip install git+https://github.com/Ana-Karem-Garcia/Math_Travel

  Cloning https://github.com/Ana-Karem-Garcia/Math_Travel to /tmp/pip-req-build-bvck7qqo
  Running command git clone --filter=blob:none --quiet https://github.com/Ana-Karem-Garcia/Math_Travel /tmp/pip-req-build-bvck7qqo
  Resolved https://github.com/Ana-Karem-Garcia/Math_Travel to commit dadcc6a5ccb99bcb6e08c93268dfcb1ac94b3cab
  Preparing metadata (setup.py) ... done
  Created wheel for MathTravel: filename=MathTravel-0.1-py3-none-any.whl size=1622 sha256=91e5da0dc248e4aa30e409011c447ebaaa65ca61cad30541a38c150bd1009a0b
  Stored in directory: /tmp/pip-ephem-wheel-cache-gyvfbkx6/wheels/45/60/6c/372a22d665f4fc53759f47ff7c75a3862a3b9b8bef378da294
Successfully built MathTravel


In [5]:
from MathTravel import calcular_costo
import numpy as np

def generar_matriz_simetrica_con_ceros_enteros(ciudades, rango_inicio=10, rango_fin=100):
    # Generar una matriz aleatoria cuadrada de enteros
    matriz = np.random.randint(rango_inicio, rango_fin, size=(ciudades, ciudades), dtype=int)

    # Hacer la matriz simétrica
    matriz_simetrica = (matriz + matriz.T) // 2

    # Establecer ceros en la diagonal
    np.fill_diagonal(matriz_simetrica, 0)

    return matriz_simetrica

# Ejemplo de uso:
ciudades = 10
matriz_costo = generar_matriz_simetrica_con_ceros_enteros(ciudades)

def calcular_costo(ciudad1, ciudad2):
    # Función para calcular el costo entre dos ciudades
    return matriz_costo[ciudad1][ciudad2]

def agente_viajero_poda(n, matriz_costo):
    #función principal, con n el número total de ciudades, matriz de costos entre ciudades
    opt_costo = None
    #almacena el mejor costo
    opt_ruta = ()
    #almacena la mejor ruta encontrada

    def _av_aux(ruta, visitadas, costo_actual):
      #ruta es una tupla que representa la ruta actual que ha sido recorrida
      #visitadas un conjunto que almacena las ciudades ya visitadas
      #costo_actual es la costo acumulada recorrida hasta ahora
      #realiza la busqueda recursiva
        nonlocal opt_costo, opt_ruta
        #no se consideran como variables locales en esta función

        if len(ruta) == n:
            # comprueba que se han visitado todas las ciudades
            costo_actual += calcular_costo(ruta[-1], ruta[0])
             #El simbolo += significa que al numero que ya esta almacenado en la variable de la izquierda, se le suma el nuevo numero que esta a la derecha del mismo
             #agregamos el costo de la ultima ciudad en la ruta de vuelta al punto de inicio
            if opt_costo is None or costo_actual < opt_costo:
                #comprueba si el costo actual es el mejor costo encontrado hasta ahora
                opt_costo = costo_actual
                #actualiza el mejor costo actual
                opt_ruta = ruta + (ruta[0],)
                #actualiza la mejor ruta agregando la ciudad del inicio al final de la ruta actual
                #ya que tenemos que formar un ciclo que regrese al punto incial
            return

        # Tratar el caso especial cuando la longitud de la ruta es cero
        if len(ruta) == 0:
            for ciudad in range(n):
                _av_aux((ciudad,), {ciudad}, 0)
        else:
            for ciudad in range(n):
              #este for recorre las ciudades en un rango de 0 a n-1
                if ciudad not in visitadas:
                  #verificamos que la ciudad actual no ha sido visitada, si ya a sido visitada se omite
                    nuevo_costo = costo_actual + calcular_costo(ruta[-1], ciudad)
                    #Calcula el costo acumulado hasta la ciudad actual, sumando el costo entre la ultima ciudad en la ruta y la ciudad actual
                    if opt_costo is None or nuevo_costo < opt_costo:
                     #comprueba si el costo calculado es el mejor que el mejor costo conocido (opt_costo)
                     #la condicion opt_costo is none maneja el caso cuando aun no se ha encontrado ninguna solucion
                        _av_aux(ruta + (ciudad,), visitadas.union({ciudad}), nuevo_costo)


    # Llamada inicial con la ciudad inicial como punto de partida
    _av_aux((), set(), 0)

    return opt_costo, opt_ruta


costo_optimo, ruta_optima = agente_viajero_poda(ciudades, matriz_costo)
print("La matriz de costos entre ciudades es:")
print(matriz_costo)
print("Costo óptimo:", costo_optimo)
print("Ruta óptima:", ruta_optima)

La matriz de costos entre ciudades es:
[[ 0 63 66 31 18 49 53 42 32 38]
 [63  0 49 51 61 20 77 29 48 60]
 [66 49  0 58 46 86 75 75 64 48]
 [31 51 58  0 63 73 55 39 48 54]
 [18 61 46 63  0 68 54 71 35 40]
 [49 20 86 73 68  0 81 68 46 68]
 [53 77 75 55 54 81  0 97 62 54]
 [42 29 75 39 71 68 97  0 35 56]
 [32 48 64 48 35 46 62 35  0 55]
 [38 60 48 54 40 68 54 56 55  0]]
Costo óptimo: 387
Ruta óptima: (0, 4, 2, 9, 6, 3, 7, 1, 5, 8, 0)
